/** 성과 사례 30개 - 필터 탭용 카테고리 */
export type CaseFilterCategory =
  | "전체"
  | "네이버 플레이스"
  | "당근마켓 동네소식"
  | "샤오홍슈/글로벌"
  | "인스타/유튜브 바이럴"
  | "배달/커머스";

export type SuccessCaseItem = {
  id: number;
  platform: string;
  category: CaseFilterCategory;
  badge: string; // 이모지+플랫폼명
  title: string;
  metrics: string;
  desc: string;
  image: string; // Unsplash placeholder
};

export const casesData: SuccessCaseItem[] = [
  {
    id: 1,
    platform: "네이버 플레이스",
    category: "네이버 플레이스",
    badge: "🟢 네이버",
    title: "강남역 200평 고깃집, 빈 테이블에서 일 매출 1천만 원 달성",
    metrics: "메인 키워드 1페이지 장악",
    desc: "주변 직장인 타겟 검색량 분석 후, 영수증 리뷰와 블로그 시딩을 최적화하여 3주 만에 단체 회식 예약 풀 부킹 달성.",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
  },
  {
    id: 2,
    platform: "당근마켓 동네소식",
    category: "당근마켓 동네소식",
    badge: "🥕 당근마켓",
    title: "동네 골목 미용실, 당근 지역 광고로 신규 단골 300명 확보",
    metrics: "당근 단골 맺기 500% 폭증",
    desc: "단순 할인이 아닌 '원장님의 헤어 철학'을 담은 동네소식 발행과 지역 타겟팅 광고로 맘카페 입소문까지 연결.",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
  },
  {
    id: 3,
    platform: "샤오홍슈",
    category: "샤오홍슈/글로벌",
    badge: "📕 샤오홍슈",
    title: "홍대 K-뷰티 에스테틱, 중국인 관광객 필수 코스로 등극",
    metrics: "해외 고객 방문율 400% 상승",
    desc: "샤오홍슈 뷰티 왕홍(인플루언서) 배포 및 상세한 한국 여행 코스형 콘텐츠 기획으로 방한 전 선예약 유도.",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
  },
  {
    id: 4,
    platform: "인스타그램 릴스",
    category: "인스타/유튜브 바이럴",
    badge: "📸 인스타 릴스",
    title: "성수동 팝업스토어, 릴스 바이럴로 주말 대기 2천 명 돌파",
    metrics: "조회수 150만, 웨이팅 3시간",
    desc: "비주얼을 극대화한 숏폼 템플릿 기획 및 마이크로 인플루언서 동시 다발적 업로드로 2030 핫플 등극.",
    image: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&q=80",
  },
  {
    id: 5,
    platform: "유튜브 브랜딩",
    category: "인스타/유튜브 바이럴",
    badge: "▶ 유튜브",
    title: "강남 대형 치과, 정보성 영상으로 고관여 환자 DB 싹쓸이",
    metrics: "임플란트 문의 월 150건 증가",
    desc: "원장님의 신뢰도를 높이는 기획 촬영 및 유튜브 SEO(검색 최적화) 세팅으로 유튜브 검색 유입 극대화.",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80",
  },
  {
    id: 6,
    platform: "네이버 블로그",
    category: "네이버 플레이스",
    badge: "🟢 네이버 블로그",
    title: "판교 정형외과, 개원 1달 만에 초진 환자 예약 마감",
    metrics: "지역 의료 키워드 상위 노출",
    desc: "공장형 원고가 아닌, 환자들의 통증 키워드(Pain Point)를 분석한 전문성 있는 질환 정보 포스팅 발행.",
    image: "https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?w=800&q=80",
  },
  {
    id: 7,
    platform: "배달앱 (배민/쿠팡이츠)",
    category: "배달/커머스",
    badge: "🛵 배달앱",
    title: "부천 배달 전문 야식집, 깃발 최적화로 카테고리 1위",
    metrics: "주문 수 3배, 찜 2,000개 돌파",
    desc: "무분별한 깃발 꽂기를 중단하고, 데이터 기반 핫스팟 타겟팅 및 썸네일/리뷰 이벤트 전면 개편.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  },
  {
    id: 8,
    platform: "스마트스토어",
    category: "배달/커머스",
    badge: "🛒 스마트스토어",
    title: "신생 여성 의류 쇼핑몰, 리뷰 최적화로 베스트 10 진입",
    metrics: "구매 전환율 8% 달성",
    desc: "가구매/가리뷰 등 어뷰징 없이, 체험단 포토 리뷰 선행 작업으로 초기 고객의 구매 망설임을 완벽 해결.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
  },
  {
    id: 9,
    platform: "당근마켓 지역광고",
    category: "당근마켓 동네소식",
    badge: "🥕 당근 지역광고",
    title: "수원 대형 필라테스, 전단지 끊고 당근으로 오픈 멤버 조기 마감",
    metrics: "상담 문의 250건, 등록률 60%",
    desc: "운동 목적별(다이어트, 체형교정) A/B 테스트 광고 소재 기획 및 동네 커뮤니티 친화적 소통 운영.",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80",
  },
  {
    id: 10,
    platform: "맘카페",
    category: "당근마켓 동네소식",
    badge: "💬 맘카페",
    title: "동탄 영어학원, 설명회 3일 전 전 좌석 예약 마감",
    metrics: "설명회 참석률 100%",
    desc: "노골적인 홍보를 배제하고, 지역 학부모들의 교육 고민을 나누는 자연스러운 정보성 게시글로 신뢰도 구축.",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80",
  },
  {
    id: 11,
    platform: "네이버 플레이스",
    category: "네이버 플레이스",
    badge: "🟢 네이버",
    title: "압구정 한의원, 검색 1페이지 고정 후 초진 대기 2주",
    metrics: "체형교정 키워드 1위",
    desc: "한의원 특화 키워드와 영수증 리뷰 전략으로 지역 검색 상위를 장악하고, 예약 전환 랜딩까지 일원화.",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=800&q=80",
  },
  {
    id: 12,
    platform: "당근마켓 동네소식",
    category: "당근마켓 동네소식",
    badge: "🥕 당근마켓",
    title: "잠실 카페, 동네 맛집으로 입소문 나니 주말 웨이팅 일상",
    metrics: "당근 저장 1,200개",
    desc: "로스터리와 시그니처 메뉴 스토리를 동네소식에 담아 발행하고, 지역 타겟 광고로 첫 방문객 유입.",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
  },
  {
    id: 13,
    platform: "샤오홍슈",
    category: "샤오홍슈/글로벌",
    badge: "📕 샤오홍슈",
    title: "청담 피부과, K-뷰티 관광 코스로 해외 예약 3배",
    metrics: "중국인 선예약 월 80건",
    desc: "의료법을 준수한 브랜드 스토리와 왕홍 콜라보로 방한 전 검색·예약까지 한 번에 연결.",
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&q=80",
  },
  {
    id: 14,
    platform: "인스타그램",
    category: "인스타/유튜브 바이럴",
    badge: "📸 인스타",
    title: "이태원 와인바, 인스타 그램으로 연인 데이트 1순위 등극",
    metrics: "주말 예약 2주 전 마감",
    desc: "분위기와 메뉴 비주얼에 맞춘 그램 전략과 마이크로 인플루언서 협업으로 20·30대 유입 극대화.",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80",
  },
  {
    id: 15,
    platform: "유튜브",
    category: "인스타/유튜브 바이럴",
    badge: "▶ 유튜브",
    title: "강남 변호사 사무실, 유튜브 법률 정보로 상담 문의 폭주",
    metrics: "채널 구독 5만, 상담 전환 40%",
    desc: "일상 법률 궁금증을 해결하는 정보성 영상 시리즈로 검색 유입을 확보하고, 상담 신청으로 자연스럽게 연결.",
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
  },
  {
    id: 16,
    platform: "네이버 플레이스",
    category: "네이버 플레이스",
    badge: "🟢 네이버",
    title: "역삼 헬스장, 플레이스·지도 동시 상위로 신규 회원 200명",
    metrics: "지역 헬스 1위 노출",
    desc: "시설 사진·운영 시간·가격 정보 정리와 실이용자 후기 관리로 검색 시 상위 고정.",
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
  },
  {
    id: 17,
    platform: "쿠팡",
    category: "배달/커머스",
    badge: "🟠 쿠팡",
    title: "주방용품 브랜드, 쿠팡 베스트 10 진입 후 월 매출 2억",
    metrics: "카테고리 3위, 리뷰 5,000+",
    desc: "로켓배송 품질과 포토 리뷰 시딩 전략을 결합해 검색 노출과 구매 전환을 동시에 끌어올림.",
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
  },
  {
    id: 18,
    platform: "당근마켓",
    category: "당근마켓 동네소식",
    badge: "🥕 당근마켓",
    title: "분당 인테리어 업체, 당근 후기로 단체 시공 문의 쏟아짐",
    metrics: "동네 시공 문의 월 50건",
    desc: "시공 전후 비교와 시공 과정을 담은 동네소식으로 신뢰를 쌓고, 입주민 단체 시공까지 연계.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
  },
  {
    id: 19,
    platform: "샤오홍슈",
    category: "샤오홍슈/글로벌",
    badge: "📕 샤오홍슈",
    title: "명동 네일샵, 중국인 관광객 필수 체험 코스로 등록",
    metrics: "해외 방문객 비중 60%",
    desc: "K-뷰티 네일 트렌드를 담은 왕홍 콘텐츠와 예약 링크 세팅으로 방한 전 예약 유도.",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&q=80",
  },
  {
    id: 20,
    platform: "인스타그램 릴스",
    category: "인스타/유튜브 바이럴",
    badge: "📸 릴스",
    title: "건대 베이커리, 릴스 한 편으로 전국 택배 주문 폭주",
    metrics: "조회 80만, 주문 300% 증가",
    desc: "빵 제작 과정과 시그니처 메뉴를 숏폼으로 압축해 바이럴 시드 뿌리기 및 택배 링크 전환.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
  },
  {
    id: 21,
    platform: "네이버 블로그",
    category: "네이버 플레이스",
    badge: "🟢 네이버 블로그",
    title: "송파 치과, 블로그 검색 1페이지로 임플란트 문의 월 100건",
    metrics: "지역 치과 키워드 상위",
    desc: "환자 관점 질환·치료 정보 포스팅과 플레이스 연동으로 검색 유입부터 예약까지 한 흐름 구축.",
    image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800&q=80",
  },
  {
    id: 22,
    platform: "요기요",
    category: "배달/커머스",
    badge: "🛵 요기요",
    title: "강남 족발집, 깃발·리뷰 전략으로 구역 1위 달성",
    metrics: "주문 수 2배, 평점 4.8",
    desc: "핫스팟 데이터 기반 깃발 배치와 리뷰 이벤트로 노출·전환을 동시에 끌어올려 카테고리 1위.",
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&q=80",
  },
  {
    id: 23,
    platform: "스마트스토어",
    category: "배달/커머스",
    badge: "🛒 스마트스토어",
    title: "건강기능식품 쇼핑몰, 리뷰 최적화로 구매 전환율 2배",
    metrics: "전환율 6% → 12%",
    desc: "실제 복용 후기와 성분 설명을 체계적으로 쌓아 검색 신뢰도와 장바구니 전환을 동시에 개선.",
    image: "https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&q=80",
  },
  {
    id: 24,
    platform: "당근마켓",
    category: "당근마켓 동네소식",
    badge: "🥕 당근마켓",
    title: "수원 태권도장, 당근 지역 광고로 원생 모집 조기 마감",
    metrics: "상담 180건, 등록 70명",
    desc: "체육관 시설과 수업 분위기를 동네소식으로 알리고, 학부모 타겟 광고로 상담·등록 전환.",
    image: "https://images.unsplash.com/photo-1547347298-4074fc3086f0?w=800&q=80",
  },
  {
    id: 25,
    platform: "네이버 플레이스",
    category: "네이버 플레이스",
    badge: "🟢 네이버",
    title: "마곡 한식당, 플레이스 1페이지로 점심 단체 예약 풀",
    metrics: "메인 키워드 1~3위",
    desc: "직장인 점심·회식 검색 키워드 분석 후 영수증 리뷰와 메뉴 사진 최적화로 3주 만에 상위 고정.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
  },
  {
    id: 26,
    platform: "유튜브",
    category: "인스타/유튜브 바이럴",
    badge: "▶ 유튜브",
    title: "성남 피부과, 유튜브 정보 영상으로 시술 문의 월 200건",
    metrics: "채널 구독 3만, 검색 유입 80%",
    desc: "피부 고민별 정보성 영상 시리즈와 SEO 세팅으로 유튜브 검색 시 상위 노출, 병원 예약으로 연결.",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
  },
  {
    id: 27,
    platform: "쿠팡이츠",
    category: "배달/커머스",
    badge: "🛵 쿠팡이츠",
    title: "광진구 치킨집, 쿠팡이츠 최적화로 주문 수 2.5배",
    metrics: "구역 내 5위 → 1위",
    desc: "썸네일·메뉴 구성·리뷰 관리 전면 개편으로 클릭률과 재주문률을 동시에 상승.",
    image: "https://images.unsplash.com/photo-1567620832903-0fc676de4786?w=800&q=80",
  },
  {
    id: 28,
    platform: "맘카페",
    category: "당근마켓 동네소식",
    badge: "💬 맘카페",
    title: "판교 피아노학원, 맘카페 입소문으로 신규 원생 50명",
    metrics: "설명회 참석 100% 전환",
    desc: "교육 철학과 원장님 인터뷰를 담은 정보성 글을 지역 맘카페에 자연스럽게 배포해 신뢰 확보.",
    image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&q=80",
  },
  {
    id: 29,
    platform: "샤오홍슈",
    category: "샤오홍슈/글로벌",
    badge: "📕 샤오홍슈",
    title: "이태원 탈모클리닉, K-헤어 관광으로 해외 환자 유입",
    metrics: "해외 환자 비중 50%",
    desc: "한국 헤어·두피 관광 스토리를 샤오홍슈에 연재하고 예약 링크로 방한 전 예약 유도.",
    image: "https://images.unsplash.com/photo-1622287162716-f311baa18f44?w=800&q=80",
  },
  {
    id: 30,
    platform: "네이버 플레이스",
    category: "네이버 플레이스",
    badge: "🟢 네이버",
    title: "서초 법률사무소, 플레이스·블로그 연동으로 상담 예약 3배",
    metrics: "지역 변호사 검색 상위",
    desc: "법률 분야별 블로그 포스팅과 플레이스 리뷰·정보 정리로 검색 신뢰도와 상담 전환을 동시에 확보.",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
  },
];

export const CASE_FILTER_TABS: CaseFilterCategory[] = [
  "전체",
  "네이버 플레이스",
  "당근마켓 동네소식",
  "샤오홍슈/글로벌",
  "인스타/유튜브 바이럴",
  "배달/커머스",
];
